---
- hosts: "{{ hosts }}"
  tasks:
    - name: AWS Login
      shell: "aws ecr get-login-password --region {{ ecr-region }} | docker login --username AWS --password-stdin {{ ecr-url }}"


    - name: Docker Pull
      shell: "docker pull {{ ecr-url }}/{{ docker-img }}:latest"

    - name: Docker Run
      shell: "docker run --workdir=/app -p 5000:5000 {{ docker-img }}"
