---
- hosts: "{{ hosts }}"
  tasks:
    - name: Git Pull
      git: 
        repo: "{{ repoUrl }}"
        dest: "{{ repoDest }}"
      any_errors_fatal: true
  
    - name: Docker Build
      shell: "cd {{ repoDest }} && docker build -t {{ dockerImg }} ./"
  
    - name: Docker Tag
      shell: "docker tag {{ dockerImg }}:latest {{ ecrUrl }}/{{ dockerImg }}:latest"
  
    - name: AWSLogin
      shell: "aws ecr get-login-password --region {{ ecrRegion }} | docker login --username AWS --password-stdin {{ ecrUrl }}"
  
    - name: Docker push ECR
      shell: "docker push {{ ecrUrl }}/{{ dockerImg }}:latest"
  
    - name: Docker Remove Image
      shell: "docker rmi {{ dockerImg }} --force"
