---

- name: Run the test playbook
  gather_facts: false
  hosts: "{{ hosts }}"
  tasks:
    - name: Get the username running this playbook
      become: false
      local_action: command whoami
      register: username_on_the_host

    - name: Display the User name
      ansible.builtin.debug:
        msg: "Hello User {{ username_on_the_host.stdout }} Host {{ hosts }} from Jenkins and Ansible!!"
